### ISSUE TITLE
Runfiles should have public visibility or examples updated

### ISSUE THREAD

**Issue by Ekrekr** [google/sandboxed-api#79] opened 2021-01-08 11:35 UTC
Hello! Correct me if I'm wrong, but the examples won't work in external Bazel projects due to `sandboxed_api/sandbox2/util:runfiles` not having public visibility.

From my understanding the correct way to load files for sandboxing is to use `GetDataDependencyFilePath` (instead of `GetInternalDataDependencyFilePath`) which exists in `sandboxed_api/sandbox2/util/runfiles.h`, demonstrated by the examples. However `sandboxed_api/sandbox2/util:runfiles` can't be added to BUILD files in external bazel projects because it doesn't have `"//visibility:public"`.

**Comment by cblichmann** [comment] 2021-01-11 12:22
Hey there!

Yes, you're correct, the examples won't be visible in external Bazel projects. That is by design, though. Ideally, we don't want to even build the examples when the external project is built.

I added the "Enhancement" label, as using `GetDataDependencyFilePath()` would still be useful.

**Comment by cblichmann** [comment] 2021-01-14 15:15
Implemented, closing.

**Closed by cblichmann** 2021-01-14 15:15 UTC
Labels: enhancement
